package main

import (
	"bufio"
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

type resourceMeasurement struct {
	ID         string
	Backend    string
	SourceFile string
	Started    time.Time
	Stopped    time.Time
}

type containerResourceSample struct {
	MeasuredAt       time.Time
	CPUPercent       float64
	MemoryBytes      int64
	MemoryLimitBytes int64
	MemoryPercent    float64
	NetRXBytes       int64
	NetTXBytes       int64
	BlockReadBytes   int64
	BlockWriteBytes  int64
	PIDs             int
}

type hostResourceSample struct {
	MeasuredAt        time.Time
	CPUPercent        *float64
	CPUUserPercent    *float64
	CPUSystemPercent  *float64
	CPUIOWaitPercent  *float64
	CPUIdlePercent    *float64
	MemoryAvailableKB *int64
	MemoryUsedKB      *int64
	MemoryPercent     *float64
}

type hostDiskResourceSample struct {
	MeasuredAt  time.Time
	Device      string
	TPS         float64
	ReadKBS     float64
	WriteKBS    float64
	AwaitMS     float64
	UtilPercent float64
}

// ImportMeasurement reads the finished Docker stats CSV and host.txt,
// normalizes their values and stores the complete measurement in PostgreSQL.
//
// resultDir example:
//
//	measurements/nats-SRC__nats-2026-09-11-21-20-07
//
// backend:
//
//	"nats" or "kafka"
//
// runName:
//
//	the exact run name generated by the benchmark client.
//	The importer uses runName as the resource measurement ID and
//	runName+".csv" as source_file, so it matches benchmark_runs.source_file.
func ImportMeasurement(
	ctx context.Context,
	resultDir string,
	backend string,
	runName string,
) error {
	backend = strings.ToLower(strings.TrimSpace(backend))
	if backend != "kafka" && backend != "nats" {
		return fmt.Errorf("unsupported backend %q", backend)
	}

	runName = strings.TrimSpace(runName)
	runName = strings.TrimSuffix(runName, ".csv")
	if runName == "" {
		return errors.New("runName is empty")
	}

	hostPath := filepath.Join(resultDir, "host.txt")
	containerPath := filepath.Join(resultDir, backend+".csv")

	// Older versions of the measurement API used container.csv.
	if _, err := os.Stat(containerPath); err != nil {
		fallback := filepath.Join(resultDir, "container.csv")
		if _, fallbackErr := os.Stat(fallback); fallbackErr != nil {
			return fmt.Errorf(
				"container measurement not found: tried %s and %s",
				containerPath,
				fallback,
			)
		}
		containerPath = fallback
	}

	containerSamples, err := parseContainerResourceCSV(containerPath)
	if err != nil {
		return fmt.Errorf("parse %s: %w", containerPath, err)
	}

	measurement, hostSamples, diskSamples, err := parseHostResourceFile(hostPath)
	if err != nil {
		return fmt.Errorf("parse %s: %w", hostPath, err)
	}

	measurement.ID = runName
	measurement.Backend = backend
	measurement.SourceFile = runName + ".csv"

	if len(containerSamples) == 0 {
		return errors.New("container CSV contains no samples")
	}
	if len(hostSamples) == 0 {
		return errors.New("host.txt contains no CPU/RAM samples")
	}

	dbCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	conn, err := pgx.Connect(dbCtx, measurementDatabaseURL())
	if err != nil {
		return fmt.Errorf("connect to PostgreSQL: %w", err)
	}
	defer conn.Close(context.Background())

	tx, err := conn.Begin(dbCtx)
	if err != nil {
		return fmt.Errorf("begin PostgreSQL transaction: %w", err)
	}
	defer tx.Rollback(context.Background())

	// Re-importing the same run is safe: remove old child samples and insert
	// the freshly parsed measurement again.
	if _, err := tx.Exec(
		dbCtx,
		`DELETE FROM host_disk_resource_samples WHERE measurement_id = $1`,
		measurement.ID,
	); err != nil {
		return fmt.Errorf("delete old host disk samples: %w", err)
	}

	if _, err := tx.Exec(
		dbCtx,
		`DELETE FROM host_resource_samples WHERE measurement_id = $1`,
		measurement.ID,
	); err != nil {
		return fmt.Errorf("delete old host samples: %w", err)
	}

	if _, err := tx.Exec(
		dbCtx,
		`DELETE FROM container_resource_samples WHERE measurement_id = $1`,
		measurement.ID,
	); err != nil {
		return fmt.Errorf("delete old container samples: %w", err)
	}

	if _, err := tx.Exec(
		dbCtx,
		`
		INSERT INTO resource_measurements (
			id,
			backend,
			source_file,
			measurement_started,
			measurement_stopped
		)
		VALUES ($1, $2, $3, $4, $5)
		ON CONFLICT (id) DO UPDATE SET
			backend = EXCLUDED.backend,
			source_file = EXCLUDED.source_file,
			measurement_started = EXCLUDED.measurement_started,
			measurement_stopped = EXCLUDED.measurement_stopped
		`,
		measurement.ID,
		measurement.Backend,
		measurement.SourceFile,
		measurement.Started,
		measurement.Stopped,
	); err != nil {
		return fmt.Errorf("insert resource measurement: %w", err)
	}

	for _, sample := range containerSamples {
		if _, err := tx.Exec(
			dbCtx,
			`
			INSERT INTO container_resource_samples (
				measurement_id,
				measured_at,
				cpu_percent,
				memory_bytes,
				memory_limit_bytes,
				memory_percent,
				net_rx_bytes,
				net_tx_bytes,
				block_read_bytes,
				block_write_bytes,
				pids
			)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
			`,
			measurement.ID,
			sample.MeasuredAt,
			sample.CPUPercent,
			sample.MemoryBytes,
			sample.MemoryLimitBytes,
			sample.MemoryPercent,
			sample.NetRXBytes,
			sample.NetTXBytes,
			sample.BlockReadBytes,
			sample.BlockWriteBytes,
			sample.PIDs,
		); err != nil {
			return fmt.Errorf("insert container sample at %s: %w", sample.MeasuredAt, err)
		}
	}

	for _, sample := range hostSamples {
		if _, err := tx.Exec(
			dbCtx,
			`
			INSERT INTO host_resource_samples (
				measurement_id,
				measured_at,
				cpu_percent,
				cpu_user_percent,
				cpu_system_percent,
				cpu_iowait_percent,
				cpu_idle_percent,
				memory_percent,
				memory_available_kb,
				memory_used_kb
			)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
			`,
			measurement.ID,
			sample.MeasuredAt,
			sample.CPUPercent,
			sample.CPUUserPercent,
			sample.CPUSystemPercent,
			sample.CPUIOWaitPercent,
			sample.CPUIdlePercent,
			sample.MemoryPercent,
			sample.MemoryAvailableKB,
			sample.MemoryUsedKB,
		); err != nil {
			return fmt.Errorf("insert host sample at %s: %w", sample.MeasuredAt, err)
		}
	}

	for _, sample := range diskSamples {
		if _, err := tx.Exec(
			dbCtx,
			`
			INSERT INTO host_disk_resource_samples (
				measurement_id,
				measured_at,
				device,
				tps,
				read_kb_s,
				write_kb_s,
				await_ms,
				util_percent
			)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
			`,
			measurement.ID,
			sample.MeasuredAt,
			sample.Device,
			sample.TPS,
			sample.ReadKBS,
			sample.WriteKBS,
			sample.AwaitMS,
			sample.UtilPercent,
		); err != nil {
			return fmt.Errorf(
				"insert host disk sample at %s (%s): %w",
				sample.MeasuredAt,
				sample.Device,
				err,
			)
		}
	}

	if err := tx.Commit(dbCtx); err != nil {
		return fmt.Errorf("commit resource measurement: %w", err)
	}

	fmt.Printf(
		"measurement imported: id=%s backend=%s container_samples=%d host_samples=%d disk_samples=%d\n",
		measurement.ID,
		measurement.Backend,
		len(containerSamples),
		len(hostSamples),
		len(diskSamples),
	)

	return nil
}

// measurementDatabaseURL prefers a complete explicit URL.
//
// Example:
//
//	export MEASUREMENT_DB_URL='postgres://benchmark_writer:password@127.0.0.1:5433/benchmarks?sslmode=disable'
//
// If MEASUREMENT_DB_URL is not set, the function uses the same default
// writer password as the supplied observability docker-compose file.
func measurementDatabaseURL() string {
	if value := strings.TrimSpace(os.Getenv("MEASUREMENT_DB_URL")); value != "" {
		return value
	}

	password := "dev-writer-change-me" //os.Getenv("BENCHMARK_DB_WRITER_PASSWORD")
	if password == "" {
		password = "dev-writer-change-me"
	}

	return fmt.Sprintf(
		"postgres://benchmark_writer:%s@127.0.0.1:15432/benchmarks?sslmode=disable",
		password,
	)
}

func parseContainerResourceCSV(path string) ([]containerResourceSample, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	reader := csv.NewReader(file)

	header, err := reader.Read()
	if err != nil {
		return nil, err

	}

	column := make(map[string]int, len(header))
	for i, name := range header {
		name = strings.TrimSpace(name)
		name = strings.ReplaceAll(name, `\_`, `_`)
		column[name] = i
	}

	required := []string{
		"timestamp",
		"cpu",
		"mem_usage",
		"mem_percent",
		"net_io",
		"block_io",
		"pids",
	}

	for _, name := range required {
		if _, ok := column[name]; !ok {
			return nil, fmt.Errorf("missing CSV column %q", name)
		}
	}

	var samples []containerResourceSample

	for {
		row, err := reader.Read()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, err
		}

		measuredAt, err := time.Parse(
			time.RFC3339Nano,
			strings.TrimSpace(row[column["timestamp"]]),
		)
		if err != nil {
			return nil, fmt.Errorf("parse timestamp: %w", err)
		}

		cpuPercent, err := parsePercent(row[column["cpu"]])
		if err != nil {
			return nil, fmt.Errorf("parse CPU %q: %w", row[column["cpu"]], err)
		}

		memoryBytes, memoryLimitBytes, err := parseBytePair(
			row[column["mem_usage"]],
		)
		if err != nil {
			return nil, fmt.Errorf(
				"parse memory %q: %w",
				row[column["mem_usage"]],
				err,
			)
		}

		memoryPercent, err := parsePercent(row[column["mem_percent"]])
		if err != nil {
			return nil, fmt.Errorf(
				"parse memory percent %q: %w",
				row[column["mem_percent"]],
				err,
			)
		}

		netRX, netTX, err := parseBytePair(row[column["net_io"]])
		if err != nil {
			return nil, fmt.Errorf(
				"parse network I/O %q: %w",
				row[column["net_io"]],
				err,
			)
		}

		blockRead, blockWrite, err := parseBytePair(
			row[column["block_io"]],
		)
		if err != nil {
			return nil, fmt.Errorf(
				"parse block I/O %q: %w",
				row[column["block_io"]],
				err,
			)
		}

		pids, err := strconv.Atoi(strings.TrimSpace(row[column["pids"]]))
		if err != nil {
			return nil, fmt.Errorf(
				"parse pids %q: %w",
				row[column["pids"]],
				err,
			)
		}

		samples = append(samples, containerResourceSample{
			MeasuredAt:       measuredAt,
			CPUPercent:       cpuPercent,
			MemoryBytes:      memoryBytes,
			MemoryLimitBytes: memoryLimitBytes,
			MemoryPercent:    memoryPercent,
			NetRXBytes:       netRX,
			NetTXBytes:       netTX,
			BlockReadBytes:   blockRead,
			BlockWriteBytes:  blockWrite,
			PIDs:             pids,
		})
	}

	return samples, nil
}

func parseHostResourceFile(
	path string,
) (
	resourceMeasurement,
	[]hostResourceSample,
	[]hostDiskResourceSample,
	error,
) {
	file, err := os.Open(path)
	if err != nil {
		return resourceMeasurement{}, nil, nil, err
	}
	defer file.Close()

	var measurement resourceMeasurement

	hostSamplesBySecond := make(map[string]*hostResourceSample)
	var diskSamples []hostDiskResourceSample

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)

	section := ""

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "measurement_started=") {
			raw := strings.TrimSpace(
				strings.TrimPrefix(line, "measurement_started="),
			)

			measurement.Started, err = time.Parse(time.RFC3339Nano, raw)
			if err != nil {
				return resourceMeasurement{}, nil, nil, fmt.Errorf(
					"parse measurement_started: %w",
					err,
				)
			}
			continue
		}

		if strings.HasPrefix(line, "measurement_stopped=") {
			raw := strings.TrimSpace(
				strings.TrimPrefix(line, "measurement_stopped="),
			)

			measurement.Stopped, err = time.Parse(time.RFC3339Nano, raw)
			if err != nil {
				return resourceMeasurement{}, nil, nil, fmt.Errorf(
					"parse measurement_stopped: %w",
					err,
				)
			}
			continue
		}

		if strings.Contains(line, "CPU") &&
			strings.Contains(line, "%user") &&
			strings.Contains(line, "%idle") {
			section = "cpu"
			continue
		}

		if strings.Contains(line, "kbmemfree") &&
			strings.Contains(line, "%memused") {
			section = "memory"
			continue
		}

		if strings.Contains(line, "DEV") &&
			strings.Contains(line, "rkB/s") &&
			strings.Contains(line, "%util") {
			section = "disk"
			continue
		}

		if measurement.Started.IsZero() {
			continue
		}

		fields := strings.Fields(line)

		measuredAt, consumed, parseErr := parseSARClock(
			fields,
			measurement.Started,
		)
		if parseErr != nil {
			// Linux header or another non-sample line.
			continue
		}

		values := fields[consumed:]

		switch section {
		case "cpu":
			// all %user %nice %system %iowait %steal %idle
			if len(values) < 7 || values[0] != "all" {
				continue
			}

			user, err1 := strconv.ParseFloat(values[1], 64)
			system, err2 := strconv.ParseFloat(values[3], 64)
			iowait, err3 := strconv.ParseFloat(values[4], 64)
			idle, err4 := strconv.ParseFloat(values[6], 64)

			if err := errors.Join(err1, err2, err3, err4); err != nil {
				return resourceMeasurement{}, nil, nil, fmt.Errorf(
					"parse SAR CPU line %q: %w",
					line,
					err,
				)
			}

			cpu := 100.0 - idle

			sample := hostSampleForTime(hostSamplesBySecond, measuredAt)
			sample.CPUPercent = float64Ptr(cpu)
			sample.CPUUserPercent = float64Ptr(user)
			sample.CPUSystemPercent = float64Ptr(system)
			sample.CPUIOWaitPercent = float64Ptr(iowait)
			sample.CPUIdlePercent = float64Ptr(idle)

		case "memory":
			// kbmemfree kbavail kbmemused %memused ...
			if len(values) < 4 {
				continue
			}

			available, err1 := strconv.ParseInt(values[1], 10, 64)
			used, err2 := strconv.ParseInt(values[2], 10, 64)
			percent, err3 := strconv.ParseFloat(values[3], 64)

			if err := errors.Join(err1, err2, err3); err != nil {
				return resourceMeasurement{}, nil, nil, fmt.Errorf(
					"parse SAR memory line %q: %w",
					line,
					err,
				)
			}

			sample := hostSampleForTime(hostSamplesBySecond, measuredAt)
			sample.MemoryAvailableKB = int64Ptr(available)
			sample.MemoryUsedKB = int64Ptr(used)
			sample.MemoryPercent = float64Ptr(percent)

		case "disk":
			// DEV tps rkB/s wkB/s dkB/s areq-sz aqu-sz await %util
			if len(values) < 9 {
				continue
			}

			tps, err1 := strconv.ParseFloat(values[1], 64)
			read, err2 := strconv.ParseFloat(values[2], 64)
			write, err3 := strconv.ParseFloat(values[3], 64)
			await, err4 := strconv.ParseFloat(values[7], 64)
			util, err5 := strconv.ParseFloat(values[8], 64)

			if err := errors.Join(err1, err2, err3, err4, err5); err != nil {
				return resourceMeasurement{}, nil, nil, fmt.Errorf(
					"parse SAR disk line %q: %w",
					line,
					err,
				)
			}

			diskSamples = append(
				diskSamples,
				hostDiskResourceSample{
					MeasuredAt:  measuredAt,
					Device:      values[0],
					TPS:         tps,
					ReadKBS:     read,
					WriteKBS:    write,
					AwaitMS:     await,
					UtilPercent: util,
				},
			)
		}
	}

	if err := scanner.Err(); err != nil {
		return resourceMeasurement{}, nil, nil, err
	}

	if measurement.Started.IsZero() {
		return resourceMeasurement{}, nil, nil, errors.New(
			"measurement_started not found in host.txt",
		)
	}

	if measurement.Stopped.IsZero() {
		return resourceMeasurement{}, nil, nil, errors.New(
			"measurement_stopped not found in host.txt",
		)
	}

	hostSamples := make(
		[]hostResourceSample,
		0,
		len(hostSamplesBySecond),
	)

	for _, sample := range hostSamplesBySecond {
		hostSamples = append(hostSamples, *sample)
	}

	sort.Slice(
		hostSamples,
		func(i, j int) bool {
			return hostSamples[i].MeasuredAt.Before(
				hostSamples[j].MeasuredAt,
			)
		},
	)

	sort.Slice(
		diskSamples,
		func(i, j int) bool {
			if diskSamples[i].MeasuredAt.Equal(
				diskSamples[j].MeasuredAt,
			) {
				return diskSamples[i].Device < diskSamples[j].Device
			}

			return diskSamples[i].MeasuredAt.Before(
				diskSamples[j].MeasuredAt,
			)
		},
	)

	return measurement, hostSamples, diskSamples, nil
}

func parseSARClock(
	fields []string,
	measurementStart time.Time,
) (time.Time, int, error) {
	if len(fields) < 2 {
		return time.Time{}, 0, errors.New("not a SAR sample")
	}

	clock := fields[0]
	layout := "15:04:05"
	consumed := 1

	if len(fields) >= 2 &&
		(fields[1] == "AM" || fields[1] == "PM") {
		clock += " " + fields[1]
		layout = "03:04:05 PM"
		consumed = 2
	}

	parsedClock, err := time.ParseInLocation(
		layout,
		clock,
		measurementStart.Location(),
	)
	if err != nil {
		return time.Time{}, 0, err
	}

	result := time.Date(
		measurementStart.Year(),
		measurementStart.Month(),
		measurementStart.Day(),
		parsedClock.Hour(),
		parsedClock.Minute(),
		parsedClock.Second(),
		0,
		measurementStart.Location(),
	)

	// Handles the rare case that a measurement crosses midnight.
	if result.Before(measurementStart.Add(-12 * time.Hour)) {
		result = result.Add(24 * time.Hour)
	}

	return result, consumed, nil
}

func hostSampleForTime(
	samples map[string]*hostResourceSample,
	t time.Time,
) *hostResourceSample {
	key := t.Format(time.RFC3339)

	if sample, ok := samples[key]; ok {
		return sample
	}

	sample := &hostResourceSample{
		MeasuredAt: t,
	}
	samples[key] = sample

	return sample
}

func parsePercent(value string) (float64, error) {
	value = strings.TrimSpace(value)
	value = strings.TrimSuffix(value, "%")
	return strconv.ParseFloat(value, 64)
}

var dockerByteValuePattern = regexp.MustCompile(
	`(?i)^\s*([0-9]+(?:\.[0-9]+)?)\s*([kmgt]?i?b)\s*$`,
)

func parseDockerBytes(value string) (int64, error) {
	match := dockerByteValuePattern.FindStringSubmatch(
		strings.TrimSpace(value),
	)
	if match == nil {
		return 0, fmt.Errorf("unsupported byte value %q", value)
	}

	number, err := strconv.ParseFloat(match[1], 64)
	if err != nil {
		return 0, err
	}

	multipliers := map[string]float64{
		"b":   1,
		"kb":  1_000,
		"mb":  1_000_000,
		"gb":  1_000_000_000,
		"tb":  1_000_000_000_000,
		"kib": 1024,
		"mib": 1024 * 1024,
		"gib": 1024 * 1024 * 1024,
		"tib": 1024 * 1024 * 1024 * 1024,
	}

	multiplier, ok := multipliers[strings.ToLower(match[2])]
	if !ok {
		return 0, fmt.Errorf("unsupported unit %q", match[2])
	}

	return int64(number * multiplier), nil
}

func parseBytePair(value string) (int64, int64, error) {
	parts := strings.Split(value, "/")
	if len(parts) != 2 {
		return 0, 0, fmt.Errorf(
			"expected '<value> / <value>', got %q",
			value,
		)
	}

	left, err := parseDockerBytes(parts[0])
	if err != nil {
		return 0, 0, err
	}

	right, err := parseDockerBytes(parts[1])
	if err != nil {
		return 0, 0, err
	}

	return left, right, nil
}

func float64Ptr(value float64) *float64 {
	return &value
}

func int64Ptr(value int64) *int64 {
	return &value
}
